# Generated by Django 4.1.1 on 2022-10-03 16:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usercustom_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='city',
        ),
        migrations.RemoveField(
            model_name='usercustom',
            name='country',
        ),
        migrations.RemoveField(
            model_name='usercustom',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
