# Generated by Django 4.1.1 on 2022-10-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_address_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='company',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
