# Generated by Django 4.1.1 on 2022-10-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_image_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], default='False', max_length=20, null=True),
        ),
    ]
